Repository Spark-Project-Pulse/codehive-backend, pull requests merged in 2024-10, with the labels that each got.

#6 Refactor/django orm and api
  .github/workflows/deploy.yml
  Pipfile
  Pipfile.lock
  README.md
  backend/repositories/question_repository.py
  backend/settings.py
  backend/supabase_utils.py
  backend/urls.py
  backend/views/question_views.py
  pulse/__init__.py
  pulse/admin.py
  pulse/apps.py
  pulse/migrations/0001_initial.py
  pulse/migrations/0002_users_test.py
  pulse/migrations/0003_remove_users_test.py
  pulse/migrations/0004_alter_answers_answer_id_alter_answers_created_at_and_more.py
  pulse/migrations/0005_answers_question.py
  pulse/migrations/__init__.py
  pulse/models.py
  pulse/repositories/question_repository.py
  pulse/serializers.py
  pulse/supabase_utils.py
  pulse/tests.py
  pulse/urls/__init__.py
  pulse/urls/question_urls.py
  pulse/views/__init__.py
  pulse/views/question_views.py
Labels: enhancement

#7 Fixed bug in `deploy.sh` (need backslashes)
  .github/workflows/deploy.yml
Labels: fix

#13 Debugging backend CORS_ALLOWED_ORIGINS
  backend/settings.py
Labels: bug

#14 Bug fix: reordered middleware
  backend/settings.py
Labels: fix

#22 Chore/cleanup supabase and readme
  README.md
  pulse/migrations/0007_remove_answers_delete_me_pls_god.py
  pulse/models.py
Labels: enhancement

#31 fixed cors policy
  .github/workflows/deploy.yml
  backend/development.py
  backend/production.py
  backend/settings.py
Labels: fix

#20 Feature/pr dependency workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-dependencies.yml
Labels: feature

#19 Feature/artifact registry policy
  .github/workflows/artifact-policy-deploy.yml
  artifact-registry-policy.json
Labels: feature

#38 changed minimum docker instances in deployment script to 0
  .github/workflows/deploy.yml
Labels: fix

#42 Linked github repo to `project` on backend
  pulse/migrations/0013_projects_repo_full_name.py
  pulse/models.py
Labels: feature

#56 migrations and search vector added for questions
  pulse/migrations/0010_alter_projects_tags_alter_questions_tags.py
  pulse/migrations/0014_merge_20241018_1854.py
  pulse/migrations/0015_questions_search_vector_and_more.py
  pulse/models.py
  pulse/serializers.py
Labels: enhancement

#62 Initial community implementation
  pulse/migrations/0020_communities_communitymembers.py
  pulse/migrations/0021_communities_search_vector_and_more.py
  pulse/migrations/0022_alter_communities_title.py
  pulse/migrations/0023_alter_communities_avatar_url.py
  pulse/models.py
  pulse/serializers.py
  pulse/urls/__init__.py
  pulse/urls/community_urls.py
  pulse/views/community_views.py
Labels: feature
