Repository Spark-Project-Pulse/codehive-backend, pull requests merged in 2024-11, with the labels that each got.

#63 Implemented basic communities
  pulse/migrations/0024_questions_related_community.py
  pulse/migrations/0025_communitymembers_community_reputation_and_more.py
  pulse/migrations/0026_communitymembers_contributions.py
  pulse/models.py
  pulse/serializers.py
  pulse/urls/community_urls.py
  pulse/views/answer_views.py
  pulse/views/community_views.py
  pulse/views/question_views.py
Labels: feature

#68 Feat/will/notifications
  pulse/migrations/0029_notifications.py
  pulse/models.py
  pulse/serializers.py
  pulse/urls/__init__.py
  pulse/urls/notification_urls.py
  pulse/views/answer_views.py
  pulse/views/notification_views.py
  pulse/views/tag_views.py
  services/notification_service.py
Labels: feature

#70 Trying to fix deployment bug
  pulse/migrations/0030_alter_notifications_notification_type.py
Labels: fix, bug

#71 fixed error (maybe)
  Pipfile
  Pipfile.lock
Labels: fix

#72 attempting a fix (pls work)
  .github/workflows/deploy.yml
  pulse/supabase_utils.py
Labels: fix

#82 forgot to add this to Matt's PR
  README.md
Labels: enhancement

#84 Feat/will/notifications continued backend
  pulse/urls/notification_urls.py
  pulse/views/notification_views.py
  services/notification_service.py
Labels: feature

#85 Created AI code review feature
  Pipfile
  Pipfile.lock
  backend/settings.py
  pulse/urls/answer_urls.py
  pulse/urls/project_urls.py
  pulse/views/project_views.py
  services/ai_model_service.py
Labels: feature

#80 added test sql query
  insert-100-test-questions.sql
Labels: feature

#90 Hotfix/will/pls god fix hosts
  backend/production.py
Labels: bug

#91 allowed hosts is for backend host 😭
  backend/production.py
Labels: fix

#92 Commented out image moderation model
  pulse/supabase_utils.py
Labels: fix
