Repository Spark-Project-Pulse/codehive-backend, pull requests merged in 2024-12, with the labels that each got.

#94 Refactor/will/serverless ai models
  Pipfile
  Pipfile.lock
  pulse/supabase_utils.py
  pulse/views/answer_views.py
  pulse/views/comment_views.py
  pulse/views/community_views.py
  pulse/views/question_views.py
  pulse/views/user_views.py
  services/ai_model_service.py
Labels: fix, enhancement

#96 Refactor/make authenticated requests to backend
  .github/workflows/deploy.yml
Labels: enhancement

#98 Renamed all occurrences of communities to hives
  README.md
  pulse/migrations/0039_remove_questions_related_community_and_more.py
  pulse/models.py
  pulse/serializers.py
  pulse/urls/__init__.py
  pulse/urls/community_urls.py
  pulse/urls/hive_urls.py
  pulse/views/answer_views.py
  pulse/views/hive_views.py
  pulse/views/question_views.py
  services/notification_service.py
  sql/questions/insert-100-test-questions.sql
Labels: enhancement

#100 Fixed hive url naming
  pulse/urls/hive_urls.py
Labels: fix

#101 Support for multiple lines of code (backend)
  pulse/migrations/0041_rename_code_context_line_number_questions_code_context_line_number_start_and_more.py
  pulse/models.py
Labels: enhancement
